### ISSUE TITLE
Course import is not working

### ISSUE THREAD

**Issue by rmoch** [openfun/fun-platform#28]
## Expected Behavior
We should be able to import a complete course as a tar.gz in the CMS 

## Actual Behavior
When doing so, the import never go further "Updating course" step and stay there forever

![capture d ecran 2018-06-19 a 09 30 15](https://user-images.githubusercontent.com/89626/41583067-b590ce8a-73a3-11e8-93b8-d1884b51dc14.png)

## Steps to Reproduce
go to fun-mooc.fr to export an actual course, CMS: tools>export
in your fun-platform instance CMS: Create new course then: tools>import

## Specifications
dogwood branches

**Comment by jmaupetit** [comment]
Have you also tried to import a course via the dedicated management command?

```
$ python manage.py cms import /path/to/course
```

**Comment by sampaccoud** [comment]
This issue has been fixed by this PR https://github.com/openfun/fun-platform/pull/54
