### ISSUE TITLE
Fix docker-compose file image tags

### ISSUE THREAD

**Issue by jmaupetit** [openfun/fun-platform#9]
## Purpose

Project images should be tagged with Open edX release name (_e.g._ `ginkgo.1`) and flagged with`-dev` for development containers: `edxapp:ginkgo.1` or `edxapp:ginkgo.1-dev`. But this tagging schema can occur while publishing a container.

For now, those tags are hard coded for the `ginkgo.1` release in our `docker-compose.yml` file. I think, it can be more generic for a local usage (until we develop our flavors generator).

## Proposal

Let's switch to `edxapp:latest` and `edxapp:dev` for now.

**Comment by sampaccoud** [comment]
It occured to me that -dev is more a "different kind of image" for different uses than a "different version of a given image". So it might make more sense to have:
**edxapp:latest** and **edxapp-dev:latest**

**Comment by jmaupetit** [comment]
I am not sure if we want to stick to "the docker way" to prepare images. Take a look at tags (or flavors) available for the python image: https://hub.docker.com/_/python/
